def undertale ():
    print "long"
    print "ago"
    print "humans"
    print "and"
    print "monsters"
    print "fought"
    print "for"
    print "the"
    print "surface"
    print "humans"
    print "won"
    print "banishing"
    print "the"
    print "monsters"
    print "to"
    print "the"
    print "underland"
    print "to"
    print "sufferETERNALLYHEEHEE"
   
